name: gradution_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_custom_dropdown: ^3.0.0
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chat_bubbles: 1.5.0
  cherry_toast: ^1.10.1
  cloud_firestore: ^4.13.3
  custom_radio_grouped_button: any
  dartz: ^0.10.1
  day_night_time_picker: ^1.3.1
  dio: ^5.4.1
  dotted_border: ^2.1.0
  easy_date_timeline: ^1.0.3
  equatable: ^2.0.5
  extended_tabs: ^4.1.0
  file_picker: ^6.1.1
  firebase_auth: ^4.15.5
  firebase_core: 2.27.0
  firebase_storage: 11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_maps_flutter: 2.5.3
  google_nav_bar: ^5.0.6
  jiffy: 6.2.1
  line_icons: ^2.0.3
  path_provider: ^2.1.2
  pdf: ^3.10.8
  permission_handler: ^11.3.0
  printing: ^5.12.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/patients/
    - assets/images/doctor/
    - assets/svg/
    - assets/translations/ar.json
    - assets/translations/en.json

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Black.ttf
