// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBD5lgBk94yqPoWQDu7t3oh26qF0qrRg',
    appId: '1:223980964385:web:0460c4cdc0bdf35d1cb160',
    messagingSenderId: '223980964385',
    projectId: 'clitech',
    authDomain: 'clitech.firebaseapp.com',
    storageBucket: 'clitech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD054182URZ544uobGJ7pVuJlaOqXVJyRw',
    appId: '1:223980964385:android:f87f980b278c9b2a1cb160',
    messagingSenderId: '223980964385',
    projectId: 'clitech',
    storageBucket: 'clitech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2nuI0dO5SB_sGif2FKRf2S3gbAascSQ',
    appId: '1:223980964385:ios:77c70bb42885a7d01cb160',
    messagingSenderId: '223980964385',
    projectId: 'clitech',
    storageBucket: 'clitech.appspot.com',
    iosBundleId: 'com.example.gradutionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2nuI0dO5SB_sGif2FKRf2S3gbAascSQ',
    appId: '1:223980964385:ios:77c70bb42885a7d01cb160',
    messagingSenderId: '223980964385',
    projectId: 'clitech',
    storageBucket: 'clitech.appspot.com',
    iosBundleId: 'com.example.gradutionProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBBD5lgBk94yqPoWQDu7t3oh26qF0qrRg',
    appId: '1:223980964385:web:facca4de2e97a0041cb160',
    messagingSenderId: '223980964385',
    projectId: 'clitech',
    authDomain: 'clitech.firebaseapp.com',
    storageBucket: 'clitech.appspot.com',
  );

}